version: '3'

services: 

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./config.d:/etc/nginx/conf.d/
    networks:
     - node-network
    ports: 
      - "8080:80"
  app:
    image: node:16
    user: node
    working_dir: /usr/src/app/
    command: bash -c "npm install && node index.js"
    volumes:
      - ./:/usr/src/app
    container_name: node
    networks: 
      - node-network
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    
networks: 
  node-network:
    driver: bridge 